version: "3.9"  

services:
  
  springboot-project:
    build: .  
    ports:
      - "8081:8081"  
    environment:
      MYSQL_HOST: mysqlcontainer  
      MYSQL_PORT: 3306             
      MYSQL_DB_NAME: demo           
      MYSQL_USER: root              
      MYSQL_PASSWORD: root 
    networks:
      - networkmysql         
    depends_on:
      - mysqlcontainer  

  
  mysqlcontainer:
    image: mysql:8.0 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: demo      
    
    networks:
      - networkmysql  
    
networks:
  networkmysql:
    external: false  
